projects/content/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ContentForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])
    #text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Submit')

projects/__init__.py
import os
from flask import Flask

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecret'

from projects.content.views import content_tool
from core.views import core

app.register_blueprint(content_tool)
app.register_blueprint(core)

projects/content/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from projects.content.forms import ContentForm
from projects.content.search import searchbot

content_tool = Blueprint('content_tool', __name__)

@content_tool.route('/search', methods=['GET', 'POST'])
def search():
    form = ContentForm()
    searchObj = searchbot()
    if form.validate_on_submit():

        title = form.title.data
        summary, description, length = searchObj.bot(title)
        return render_template('search_results.html', summary = summary, description = description, length = length, content_tool = content_tool)

    return render_template('search_page.html', form = form)

projects/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title>Python Projects</title>
  </head>
  <body>

    <ul class='nav'>

      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">Home</a>
      </li>

      <li class='nav-link'>
        <a href="{{url_for('content_tool.search')}}">Content Tool</a>
      </li>

      <li class='nav-link'>
        <a href="{{url_for('content_tool.search')}}">Media Search Tool</a>
      </li>

      <li class='nav-link'>
        <a href="{{url_for('content_tool.search')}}">REST API</a>
      </li>

    </ul>

<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

projects/templates/index.html
{% extends "base.html" %}
{% block content %}

  <br>
  <div class="jumbotron text-center">
  <h1>Python Projects</h1>
  <p>Made with Flask!</p>
  </div>
  <br>

  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h3>Flask</h3>
        <p>Flask (source code) is a Python web framework built with a small core and easy-to-extend philosophy.</p>
      </div>
      <div class="col-sm-4">
        <h3>SQL</h3>
        <p>SQL is a standard language for storing, manipulating and retrieving data in databases.</p>
      </div>
      <div class="col-sm-4">
        <h3>HTML</h3>
        <p>HTML is the standard markup language for Web pages. With HTML you can create your own Website.</p>
      </div>
    </div>
  </div>

{% endblock %}

projects/templates/search_page.html
{% extends "base.html" %}
{% block content %}

    <h1>Content Search Tool</h1><br>
    <h2>Enter your search keyword here</h2><br>
  <body>
      <br>
      <div class="container">
        <form method="POST">
          {{ form.hidden_tag() }}
          {{ form.title.label }} {{ form.title() }}
          {{ form.submit() }}
        </form>
      </div>
  </body>

{% endblock %}

projects/templates/search_results.html
{% extends "base.html" %}
{% block content %}

  <body>
    <h1>Search Content</h1>
    <form class="" action= "{{url_for('content_tool.search')}}" method="post">
      <input type="submit" value="Back to Search Page">
    </form>
    <h2>Your search results:</h2>
    <ol>
    {% for link in summary %}
    <li class="page-item disabled">
      <h3>Website:</h3>
      <a href="{{link}}">{{ link }}</a> <br>
      <h3>Summary:</h3>
      {{ summary[link] }} <br>
      <h3>Content:</h3>
      {{ description[link] }} <br>
      <h3>Word Count:</h3>
      {{ length[link] }} <br><br>
    </li>
    {% endfor %}
  </ol>
  </body>

{% endblock %}